language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
install:
  - composer install --no-interaction
script:
  - composer test
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v